package goodsfrom.app.omeryasar.atry;

import goodsfrom.app.omeryasar.atry.R;

import java.util.Dictionary;
import java.util.Hashtable;

public class FlagCodes {
    public static Dictionary<Integer,Integer> flagDict = new Hashtable<>();
    public FlagCodes(){
        flagDict.put(0, R.drawable.america_flag);
        flagDict.put(19,R.drawable.america_flag);
        flagDict.put(30,R.drawable.america_flag);
        flagDict.put(39,R.drawable.america_flag);
        flagDict.put(60,R.drawable.america_flag);
        flagDict.put(139,R.drawable.america_flag);
        flagDict.put(300,R.drawable.france_flag);
        flagDict.put(379,R.drawable.france_flag);
        flagDict.put(380,R.drawable.bulgaria_flag);
        flagDict.put(385,R.drawable.crotia_flag);
        flagDict.put(387,R.drawable.bosnia_flag);
        flagDict.put(40,R.drawable.germany_flag);
        flagDict.put(440,R.drawable.germany_flag);
        flagDict.put(450,R.drawable.japan_flag);
        flagDict.put(459,R.drawable.japan_flag);
        flagDict.put(490,R.drawable.japan_flag);
        flagDict.put(499,R.drawable.japan_flag);
        flagDict.put(460,R.drawable.russian_flag);
        flagDict.put(469,R.drawable.russian_flag);
        flagDict.put(470,R.drawable.kygyzstan_flag);
        flagDict.put(471,R.drawable.taivan_flag);
        flagDict.put(474,R.drawable.estonia_flag);
        flagDict.put(475,R.drawable.latvia_flag);
        flagDict.put(476,R.drawable.azerbaijan_flag);
        flagDict.put(477,R.drawable.lithuania_flag);
        flagDict.put(480,R.drawable.philipines_flag);
        flagDict.put(481,R.drawable.belarus_flag);
        flagDict.put(482,R.drawable.ukraine_flag);
        flagDict.put(485,R.drawable.armenia_flag);
        flagDict.put(486,R.drawable.georgia_flag);
        flagDict.put(487,R.drawable.kazakhstan_flag);
        flagDict.put(488,R.drawable.tajikistan_flag);
        flagDict.put(489,R.drawable.honkong_flag);
        flagDict.put(500,R.drawable.uk_flag);
        flagDict.put(509,R.drawable.uk_flag);
        flagDict.put(520,R.drawable.greece_flag);
        flagDict.put(521,R.drawable.greece_flag);
        flagDict.put(528,R.drawable.lebanon_flag);
        flagDict.put(529,R.drawable.cyprus_flag);
        flagDict.put(530,R.drawable.albania_flag);
        flagDict.put(531,R.drawable.macedonia_flag);
        flagDict.put(539,R.drawable.ireland_flag);
        flagDict.put(540,R.drawable.belgium_flag);
        flagDict.put(540,R.drawable.luxembourg_flag);
        flagDict.put(560,R.drawable.portugal_flag);
        flagDict.put(569,R.drawable.iceland_flag);
        flagDict.put(570,R.drawable.denmark_flag);
        flagDict.put(579,R.drawable.denmark_flag);
        flagDict.put(590,R.drawable.poland_flag);
        flagDict.put(594,R.drawable.romania_flag);
        flagDict.put(599,R.drawable.hungary_flag);
        flagDict.put(603,R.drawable.ghana_flag);
        flagDict.put(604,R.drawable.senegal_flag);
        flagDict.put(608,R.drawable.bahrain_flag);
        flagDict.put(609,R.drawable.mauritius_flag);
        flagDict.put(611,R.drawable.morocco_flag);
        flagDict.put(613,R.drawable.algeria_flag);
        flagDict.put(615,R.drawable.nigeria_flag);
        flagDict.put(619,R.drawable.tunisia_flag);
        flagDict.put(621,R.drawable.syria_flag);
        flagDict.put(622,R.drawable.egypt_flag);
        flagDict.put(624,R.drawable.libya_flag);
        flagDict.put(626,R.drawable.iran_flag);
        flagDict.put(627,R.drawable.kuwait_flag);
        flagDict.put(628,R.drawable.saudi_flag);
        flagDict.put(640,R.drawable.finland_flag);
        flagDict.put(649,R.drawable.finland_flag);
        flagDict.put(690,R.drawable.china_flag);
        flagDict.put(695,R.drawable.china_flag);
        flagDict.put(700,R.drawable.norway_flag);
        flagDict.put(709,R.drawable.norway_flag);
        flagDict.put(729,R.drawable.israel_flag);
        flagDict.put(730,R.drawable.sweden_flag);
        flagDict.put(739,R.drawable.sweden_flag);
        flagDict.put(741,R.drawable.salvador_flag);
        flagDict.put(742,R.drawable.honduras_flag);
        flagDict.put(744,R.drawable.costarica_flag);
        flagDict.put(745,R.drawable.panama_flag);
        flagDict.put(746,R.drawable.dominician_flag);
        flagDict.put(754,R.drawable.canada_flag);
        flagDict.put(755,R.drawable.canada_flag);
        flagDict.put(759,R.drawable.venezuela_flag);
        flagDict.put(760,R.drawable.switzerland_flag);
        flagDict.put(769,R.drawable.switzerland_flag);
        flagDict.put(770,R.drawable.colombia_flag);
        flagDict.put(771,R.drawable.colombia_flag);
        flagDict.put(773,R.drawable.uruguay_flag);
        flagDict.put(775,R.drawable.peru_flag);
        flagDict.put(777,R.drawable.bolivia_flag);
        flagDict.put(778,R.drawable.argentina_flag);
        flagDict.put(779,R.drawable.argentina_flag);
        flagDict.put(780,R.drawable.chile_flag);
        flagDict.put(786,R.drawable.ecuador_flag);
        flagDict.put(789,R.drawable.brasil_flag);
        flagDict.put(790,R.drawable.brasil_flag);
        flagDict.put(800,R.drawable.italy_flag);
        flagDict.put(839,R.drawable.italy_flag);
        flagDict.put(840,R.drawable.spain_flag);
        flagDict.put(849,R.drawable.spain_flag);
        flagDict.put(850,R.drawable.cuba_flag);
        flagDict.put(858,R.drawable.slovakia_flag);
        flagDict.put(859,R.drawable.czech_flag);
        flagDict.put(865,R.drawable.mongolia_flag);
        flagDict.put(867,R.drawable.north_korea_flag);
        flagDict.put(868,R.drawable.turkey_flag);
        flagDict.put(869,R.drawable.turkey_flag);
        flagDict.put(870,R.drawable.netherlands_flag);
        flagDict.put(879,R.drawable.netherlands_flag);
        flagDict.put(880,R.drawable.south_korea_flag);
        flagDict.put(884,R.drawable.cambodia_flag);
        flagDict.put(885,R.drawable.thailand_flag);
        flagDict.put(888,R.drawable.singapore_flag);
        flagDict.put(890,R.drawable.india_flag);
        flagDict.put(893,R.drawable.vietnam_flag);
        flagDict.put(896,R.drawable.pakistan_flag);
        flagDict.put(899,R.drawable.indonesia_flag);
        flagDict.put(900,R.drawable.austria_flag);
        flagDict.put(919,R.drawable.austria_flag);
        flagDict.put(930,R.drawable.austraila_flag);
        flagDict.put(939,R.drawable.austraila_flag);
        flagDict.put(940,R.drawable.new_zealand_flag);
        flagDict.put(949,R.drawable.new_zealand_flag);
        flagDict.put(955,R.drawable.malaysia_flag);
        flagDict.put(750,R.drawable.mexico_flag);


    }
}
